# Generated by Django 4.1.2 on 2022-11-17 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contacto_palas_rename_curso_torneo_delete_entregable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torneo',
            old_name='camada',
            new_name='categoria',
        ),
    ]
