# Generated by Django 4.1.2 on 2022-12-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='palas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='palas'),
        ),
    ]
