# Generated by Django 4.1.2 on 2022-12-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_palas_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palas',
            old_name='imagen',
            new_name='foto',
        ),
    ]
