# Generated by Django 4.1.2 on 2022-12-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_imagen_palas_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
